import { PrismaClient } from '@prisma/client';

export const petSeed = async (prisma: PrismaClient) => {
  const pets = [
    {
      location: 'Central Park, NY',
      contact: 'John Doe - 555-1234',
      gender: 'Male',
      breed: 'Labrador Retriever',
      size: 'Large',
      type: 'Dog',
      details: 'Friendly and energetic',
      color: 'Yellow',
      name: 'Buddy',
      url: 'https://example.com/buddy.jpg',
      found: false,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'Downtown LA',
      contact: 'Jane Smith - 555-5678',
      gender: 'Female',
      breed: 'Persian',
      size: 'Small',
      type: 'Cat',
      details: 'Calm and affectionate',
      color: 'White',
      name: 'Luna',
      url: 'https://example.com/luna.jpg',
      found: true,
      shelterId: 2,
      updatedBy: 2,
    },
    {
      location: 'Chicago Suburbs',
      contact: 'Jake Long - 555-8765',
      gender: 'Male',
      breed: 'German Shepherd',
      size: 'Large',
      type: 'Dog',
      details: 'Loyal and protective',
      color: 'Black and Tan',
      name: 'Max',
      url: 'https://example.com/max.jpg',
      found: false,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'Houston Heights',
      contact: 'Elena Gil - 555-4321',
      gender: 'Female',
      breed: 'Beagle',
      size: 'Medium',
      type: 'Dog',
      details: 'Curious and friendly',
      color: 'Tricolor',
      name: 'Bella',
      url: 'https://example.com/bella.jpg',
      found: false,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'Phoenix Downtown',
      contact: 'Sam Green - 555-6789',
      gender: 'Male',
      breed: 'Siamese',
      size: 'Small',
      type: 'Cat',
      details: 'Vocal and affectionate',
      color: 'Cream and Brown',
      name: 'Oliver',
      url: 'https://example.com/oliver.jpg',
      found: true,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'Philadelphia Center',
      contact: 'Anna Lee - 555-9876',
      gender: 'Female',
      breed: 'Poodle',
      size: 'Small',
      type: 'Dog',
      details: 'Smart and active',
      color: 'White',
      name: 'Daisy',
      url: 'https://example.com/daisy.jpg',
      found: true,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'San Antonio West',
      contact: 'George Cook - 555-5432',
      gender: 'Male',
      breed: 'Bulldog',
      size: 'Medium',
      type: 'Dog',
      details: 'Calm and courageous',
      color: 'Brindle',
      name: 'Rocky',
      url: 'https://example.com/rocky.jpg',
      found: false,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'San Diego Beach',
      contact: 'Lilly Adams - 555-2345',
      gender: 'Female',
      breed: 'Golden Retriever',
      size: 'Large',
      type: 'Dog',
      details: 'Friendly and intelligent',
      color: 'Golden',
      name: 'Molly',
      url: 'https://example.com/molly.jpg',
      found: true,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'Dallas Uptown',
      contact: 'Cathy White - 555-3456',
      gender: 'Male',
      breed: 'Maine Coon',
      size: 'Large',
      type: 'Cat',
      details: 'Gentle and playful',
      color: 'Brown',
      name: 'Simba',
      url: 'https://example.com/simba.jpg',
      found: false,
      shelterId: 1,
      updatedBy: 1,
    },
    {
      location: 'San Jose East',
      contact: 'Tom Brown - 555-6543',
      gender: 'Female',
      breed: 'Chihuahua',
      size: 'Small',
      type: 'Dog',
      details: 'Lively and courageous',
      color: 'Tan',
      name: 'Gigi',
      url: 'https://example.com/gigi.jpg',
      found: true,
      shelterId: 1,
      updatedBy: 1,
    },
  ];

  await prisma.pet.createMany({
    data: pets,
  });
};
