import { PrismaClient } from '@prisma/client';

export const shelterSeed = async (prisma: PrismaClient) => {
  const shelters = [
    {
      location: 'New York',
      address: '123 NY Street',
      name: 'NY Shelter',
      email: 'ny@shelter.com',
      phone: '555-0110',
      occupation: 20,
      capacity: 50,
      owner: 'John Doe',
      needs: ['food', 'blankets'],
      other_needs: 'medical supplies',
    },
    {
      location: 'Los Angeles',
      address: '456 LA Street',
      name: 'LA Shelter',
      email: 'la@shelter.com',
      phone: '555-0111',
      occupation: 10,
      capacity: 40,
      owner: 'Jane Smith',
      needs: ['volunteers'],
      other_needs: 'cleaning supplies',
    },
    {
      location: 'Chicago',
      address: '789 Chicago Street',
      name: 'Chicago Shelter',
      email: 'chicago@shelter.com',
      phone: '555-0112',
      occupation: 15,
      capacity: 30,
      owner: 'Jim Beam',
      needs: ['food', 'toys'],
      other_needs: 'bedding',
    },
    {
      location: 'Houston',
      address: '101 Houston Street',
      name: 'Houston Shelter',
      email: 'houston@shelter.com',
      phone: '555-0113',
      occupation: 5,
      capacity: 20,
      owner: 'Jake Long',
      needs: ['medical supplies'],
      other_needs: 'food',
    },
    {
      location: 'Phoenix',
      address: '121 Phoenix Street',
      name: 'Phoenix Shelter',
      email: 'phoenix@shelter.com',
      phone: '555-0114',
      occupation: 7,
      capacity: 10,
      owner: 'Elena Gil',
      needs: ['volunteers', 'blankets'],
      other_needs: 'cleaning supplies',
    },
    {
      location: 'Philadelphia',
      address: '131 Philly Street',
      name: 'Philly Shelter',
      email: 'philly@shelter.com',
      phone: '555-0115',
      occupation: 30,
      capacity: 60,
      owner: 'Anna Lee',
      needs: ['food', 'volunteers'],
      other_needs: 'medical supplies',
    },
    {
      location: 'San Antonio',
      address: '141 SA Street',
      name: 'SA Shelter',
      email: 'sa@shelter.com',
      phone: '555-0116',
      occupation: 35,
      capacity: 70,
      owner: 'George Cook',
      needs: ['blankets', 'toys'],
      other_needs: 'food',
    },
    {
      location: 'San Diego',
      address: '151 SD Street',
      name: 'SD Shelter',
      email: 'sd@shelter.com',
      phone: '555-0117',
      occupation: 40,
      capacity: 80,
      owner: 'Lilly Adams',
      needs: ['food', 'volunteers'],
      other_needs: 'medical supplies',
    },
    {
      location: 'Dallas',
      address: '161 Dallas Street',
      name: 'Dallas Shelter',
      email: 'dallas@shelter.com',
      phone: '555-0118',
      occupation: 45,
      capacity: 90,
      owner: 'Sam Green',
      needs: ['cleaning supplies', 'toys'],
      other_needs: 'food',
    },
    {
      location: 'San Jose',
      address: '171 SJ Street',
      name: 'SJ Shelter',
      email: 'sj@shelter.com',
      phone: '555-0119',
      occupation: 50,
      capacity: 100,
      owner: 'Cathy White',
      needs: ['volunteers', 'food'],
      other_needs: 'medical supplies',
    },
  ];

  for (const shelter of shelters) {
    await prisma.shelter.create({ data: { ...shelter, updatedBy: 20 } });
  }
};
